DECLARE @NR_VERSAO INT
SET @NR_VERSAO = 5

IF ISNULL((SELECT NR_VERSAO_SISTEMA FROM TB_SISTEMA), 0) = (@NR_VERSAO - 1)
BEGIN 
	BEGIN TRANSACTION

	UPDATE TB_SISTEMA SET NR_VERSAO_SISTEMA = @NR_VERSAO 

	CREATE TABLE dbo.TB_JOGO(
    	SQ_JOGO int NOT NULL PRIMARY KEY IDENTITY (1, 1),
    	SQ_FASE int NOT NULL,
    	SQ_TIME_1 int NOT NULL,
    	SQ_TIME_2 int NOT NULL,
    	NR_PLACAR_TIME_1 int NOT NULL,
    	NR_PLACAR_TIME_2 int NOT NULL
    )
    
    ALTER TABLE dbo.TB_JOGO ADD CONSTRAINT
    	FK_TB_JOGO_TB_FASE FOREIGN KEY
    	(
    	SQ_FASE
    	) REFERENCES dbo.TB_FASE
    	(
    	SQ_FASE
    	) ON UPDATE  NO ACTION 
    	 ON DELETE  NO ACTION 
    	
    ALTER TABLE dbo.TB_JOGO ADD CONSTRAINT
    	FK_TB_JOGO_TB_TIME_1 FOREIGN KEY
    	(
    	SQ_TIME_1
    	) REFERENCES dbo.TB_TIME
    	(
    	SQ_TIME
    	) ON UPDATE  NO ACTION 
    	 ON DELETE  NO ACTION 
    	
    
    ALTER TABLE dbo.TB_JOGO ADD CONSTRAINT
    	FK_TB_JOGO_TB_TIME_2 FOREIGN KEY
    	(
    	SQ_TIME_2
    	) REFERENCES dbo.TB_TIME
    	(
    	SQ_TIME
    	) ON UPDATE  NO ACTION 
    	 ON DELETE  NO ACTION 

	COMMIT
END
ELSE
BEGIN 
	RAISERROR ('A versão do Banco de dados não é a adequada para execução deste procedimento', 16, 1)
END