DECLARE @NR_VERSAO INT
SET @NR_VERSAO = 4

IF ISNULL((SELECT NR_VERSAO_SISTEMA FROM TB_SISTEMA), 0) = (@NR_VERSAO - 1)
BEGIN 
	BEGIN TRANSACTION

	UPDATE TB_SISTEMA SET NR_VERSAO_SISTEMA = @NR_VERSAO 

    CREATE TABLE dbo.TB_FASE(
    	SQ_FASE int NOT NULL PRIMARY KEY IDENTITY (1, 1),
    	SQ_CAMPEONATO int NOT NULL,
    	NM_FASE varchar(100) NOT NULL
    )
    
    ALTER TABLE dbo.TB_FASE ADD CONSTRAINT
    	FK_TB_FASE_TB_CAMPEONATO FOREIGN KEY
    	(
    	SQ_CAMPEONATO
    	) REFERENCES dbo.TB_CAMPEONATO
    	(
    	SQ_CAMPEONATO
    	) ON UPDATE  NO ACTION 
    	 ON DELETE  NO ACTION 

	COMMIT
END
ELSE
BEGIN 
	RAISERROR ('A versão do Banco de dados não é a adequada para execução deste procedimento', 16, 1)
END