DECLARE @NR_VERSAO INT
SET @NR_VERSAO = 3

IF ISNULL((SELECT NR_VERSAO_SISTEMA FROM TB_SISTEMA), 0) = (@NR_VERSAO - 1)
BEGIN 
	BEGIN TRANSACTION

	UPDATE TB_SISTEMA SET NR_VERSAO_SISTEMA = @NR_VERSAO 

    CREATE TABLE dbo.TB_TIME(
	    SQ_TIME int NOT NULL PRIMARY KEY IDENTITY (1, 1),
	    NM_TIME varchar(100) NOT NULL
    )
    
    CREATE TABLE dbo.TB_CAMPEONATO_TIME(
    	SQ_CAMPEONATO_TIME int NOT NULL PRIMARY KEY IDENTITY (1, 1),
    	SQ_CAMPEONATO int NOT NULL,
    	SQ_TIME int NOT NULL,
    	DT_INSCRICAO datetime NOT NULL,
    	NR_PONTUACAO int NOT NULL,
    	ST_ELIMINADO varchar(1) NOT NULL
    )  
    
    ALTER TABLE dbo.TB_CAMPEONATO_TIME ADD CONSTRAINT
    	FK_TB_CAMPEONATO_TIME_TB_CAMPEONATO FOREIGN KEY
    	(
    	SQ_CAMPEONATO
    	) REFERENCES dbo.TB_CAMPEONATO
    	(
    	SQ_CAMPEONATO
    	) ON UPDATE  NO ACTION 
    	 ON DELETE  NO ACTION 
    	
    
    ALTER TABLE dbo.TB_CAMPEONATO_TIME ADD CONSTRAINT
    	FK_TB_CAMPEONATO_TIME_TB_TIME FOREIGN KEY
    	(
    	SQ_TIME
    	) REFERENCES dbo.TB_TIME
    	(
    	SQ_TIME
    	) ON UPDATE  NO ACTION 
    	 ON DELETE  NO ACTION 


	COMMIT 
END
ELSE
BEGIN 
	RAISERROR ('A versão do Banco de dados não é a adequada para execução deste procedimento', 16, 1)
END