IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_CAMPEONATO_TIME_INCLUIR'))
   DROP PROCEDURE STP_CAMPEONATO_TIME_INCLUIR

GO
CREATE PROCEDURE STP_CAMPEONATO_TIME_INCLUIR(
   @SQ_CAMPEONATO INT,
   @SQ_TIME INT
)
AS
BEGIN 
    SET DATEFORMAT DMY

	DECLARE @SQ_CAMPEONATO_EXISTE INT
	DECLARE @SQ_CAMPEONATO_TIME_EXISTE INT 

	SET @SQ_CAMPEONATO_EXISTE = ISNULL((SELECT SQ_CAMPEONATO
	                                    FROM TB_CAMPEONATO WITH(NOLOCK)
										WHERE SQ_CAMPEONATO = @SQ_CAMPEONATO), 0)

	SET @SQ_CAMPEONATO_TIME_EXISTE = ISNULL((SELECT SQ_CAMPEONATO_TIME
	                                        FROM TB_CAMPEONATO_TIME WITH(TABLOCK)
											WHERE SQ_CAMPEONATO = @SQ_CAMPEONATO
											AND SQ_TIME = @SQ_TIME), 0)

	IF @SQ_CAMPEONATO_EXISTE = 0
	BEGIN 
	    SELECT 'erro' AS CT_TIPO_RETORNO, 'Registro não pode ser incluido pois o Campeonato não foi encontrado' AS CT_MENSAGEM
	END
	ELSE IF @SQ_CAMPEONATO_TIME_EXISTE <> 0
	BEGIN
	    SELECT 'erro' AS CT_TIPO_RETORNO, 'Registro não pode ser incluido pois este Time já está no Campeonato' AS CT_MENSAGEM
	END
	ELSE
	BEGIN
		INSERT INTO TB_CAMPEONATO_TIME ( SQ_CAMPEONATO,  SQ_TIME, DT_INSCRICAO, NR_PONTUACAO, ST_ELIMINADO, NR_QUANTIDADE_VITORIA, NR_COLOCACAO) 
								VALUES (@SQ_CAMPEONATO, @SQ_TIME,    GETDATE(),            0,          'N',                     0,        100)

		SELECT 'sucesso' AS CT_TIPO_RETORNO, 'Registro incluído com sucesso' AS CT_MENSAGEM, SCOPE_IDENTITY() AS CD_CHAVE_REGISTRO
	END
END
GO
