IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_CAMPEONATO_DETALHAR'))
   DROP PROCEDURE STP_CAMPEONATO_DETALHAR

GO
CREATE PROCEDURE STP_CAMPEONATO_DETALHAR(
    @SQ_CAMPEONATO INT
)
AS
BEGIN 
	SET DATEFORMAT DMY

	SELECT CAM.*, 'sucesso' AS CT_TIPO_RETORNO FROM TB_CAMPEONATO CAM WITH(NOLOCK) WHERE SQ_CAMPEONATO = @SQ_CAMPEONATO
	
END
GO