IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_CAMPEONATO_TIME_ALTERAR'))
   DROP PROCEDURE STP_CAMPEONATO_TIME_ALTERAR

GO
CREATE PROCEDURE STP_CAMPEONATO_TIME_ALTERAR(
   @SQ_CAMPEONATO_TIME INT,
   @NR_PONTUACAO INT,
   @ST_ELIMINADO VARCHAR(1)
)
AS
BEGIN 
    SET DATEFORMAT DMY

	UPDATE TB_CAMPEONATO_TIME SET NR_PONTUACAO = @NR_PONTUACAO, 
	                              ST_ELIMINADO = @ST_ELIMINADO
    WHERE SQ_CAMPEONATO_TIME = @SQ_CAMPEONATO_TIME

	SELECT 'sucesso' AS CT_TIPO_RETORNO, 'Registro alterado com sucesso' AS CT_MENSAGEM, @SQ_CAMPEONATO_TIME AS CD_CHAVE_REGISTRO
END
GO
