IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_TIME_INCLUIR'))
   DROP PROCEDURE STP_TIME_INCLUIR

GO
CREATE PROCEDURE STP_TIME_INCLUIR(
   @NM_TIME VARCHAR(100)
)
AS
BEGIN 
    SET DATEFORMAT DMY

	INSERT INTO TB_TIME (NM_TIME) VALUES (@NM_TIME)

	SELECT 'sucesso' AS CT_TIPO_RETORNO, 'Registro incluído com sucesso' AS CT_MENSAGEM, SCOPE_IDENTITY() AS CD_CHAVE_REGISTRO
END
GO