IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_TIME_CONSULTAR'))
   DROP PROCEDURE STP_TIME_CONSULTAR

GO
CREATE PROCEDURE STP_TIME_CONSULTAR(
    @NM_TIME VARCHAR(100)
)
AS
BEGIN 
	SET DATEFORMAT DMY

	DECLARE @INSTRUCAO NVARCHAR(MAX)

	SET @INSTRUCAO = ' SELECT TIM.SQ_TIME, TIM.NM_TIME, ''sucesso'' AS CT_TIPO_RETORNO
	                   FROM TB_TIME TIM WITH(NOLOCK) '

    IF @NM_TIME <> ''
	    SET @INSTRUCAO = @INSTRUCAO + ' WHERE TIM.NM_TIME = ''' + @NM_TIME + ''' '
	
	EXECUTE sp_executesql @INSTRUCAO
	
END
GO