IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_JOGO_INCLUIR'))
   DROP PROCEDURE STP_JOGO_INCLUIR

GO
CREATE PROCEDURE STP_JOGO_INCLUIR(
   @SQ_FASE INT,
   @SQ_TIME_1 INT,
   @SQ_TIME_2 INT,
   @NR_PLACAR_TIME_1 INT,
   @NR_PLACAR_TIME_2 INT
)
AS
BEGIN 
    SET DATEFORMAT DMY
	
	INSERT INTO TB_JOGO( SQ_FASE,  SQ_TIME_1,  SQ_TIME_2,  NR_PLACAR_TIME_1,  NR_PLACAR_TIME_2) 
	            VALUES (@SQ_FASE, @SQ_TIME_1, @SQ_TIME_2, @NR_PLACAR_TIME_1, @NR_PLACAR_TIME_2)
	
	SELECT 'sucesso' AS CT_TIPO_RETORNO, 'Registro incluído com sucesso' AS CT_MENSAGEM, SCOPE_IDENTITY() AS CD_CHAVE_REGISTRO
	
END
GO