IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_COLOCACAO_CAMPEONATO_TIME_CONSULTAR'))
   DROP PROCEDURE STP_COLOCACAO_CAMPEONATO_TIME_CONSULTAR

GO
CREATE PROCEDURE STP_COLOCACAO_CAMPEONATO_TIME_CONSULTAR(
    @SQ_CAMPEONATO INT
)
AS
BEGIN 
	SET DATEFORMAT DMY

	DECLARE @INSTRUCAO NVARCHAR(MAX)

	SET @INSTRUCAO = ' SELECT CAT.*, CAM.NM_CAMPEONATO, TIM.NM_TIME, ''sucesso'' AS CT_TIPO_RETORNO
                       FROM TB_CAMPEONATO_TIME CAT WITH(NOLOCK)
                       INNER JOIN TB_CAMPEONATO CAM WITH(NOLOCK) ON CAT.SQ_CAMPEONATO = CAM.SQ_CAMPEONATO
                       INNER JOIN TB_TIME TIM WITH(NOLOCK) ON CAT.SQ_TIME = TIM.SQ_TIME 
                       WHERE CAT.SQ_CAMPEONATO = ' + CAST(@SQ_CAMPEONATO AS VARCHAR(10)) + '
					   ORDER BY CAT.NR_COLOCACAO ASC, CAT.NR_PONTUACAO DESC, CAT.DT_INSCRICAO ASC '


	EXECUTE sp_executesql @INSTRUCAO
	
END
GO