IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_FASE_INCLUIR'))
   DROP PROCEDURE STP_FASE_INCLUIR

GO
CREATE PROCEDURE STP_FASE_INCLUIR(
   @SQ_CAMPEONATO INT,
   @NM_FASE VARCHAR(100)
)
AS
BEGIN 
    SET DATEFORMAT DMY

	DECLARE @SQ_CAMPEONATO_ALVO INT 

	--Verifica se o campeonato existe na base
	SET @SQ_CAMPEONATO_ALVO = ISNULL((SELECT SQ_CAMPEONATO 
	                                  FROM TB_CAMPEONATO WITH(NOLOCK) 
									  WHERE SQ_CAMPEONATO = @SQ_CAMPEONATO), 0)
	IF @SQ_CAMPEONATO = 0
	BEGIN 
	   SELECT 'erro' AS CT_TIPO_RETORNO, 'Não foi possível incluir o registro pois o Campeonato especificado não foi encontrado' AS CT_MENSAGEM
	END
	ELSE
	BEGIN 
	   INSERT INTO TB_FASE(SQ_CAMPEONATO, NM_FASE) VALUES (@SQ_CAMPEONATO, @NM_FASE)
	   
	   SELECT 'sucesso' AS CT_TIPO_RETORNO, 'Registro incluído com sucesso' AS CT_MENSAGEM, SCOPE_IDENTITY() AS CD_CHAVE_REGISTRO
	END
END
GO