IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_CAMPEONATO_DETALHAR'))
   DROP PROCEDURE STP_CAMPEONATO_DETALHAR

GO
CREATE PROCEDURE STP_CAMPEONATO_DETALHAR(
    @SQ_CAMPEONATO INT
)
AS
BEGIN 
	SET DATEFORMAT DMY

	SELECT CAM.*, TIM.NM_TIME AS NM_TIME_CAMPEAO, 'sucesso' AS CT_TIPO_RETORNO 
	FROM TB_CAMPEONATO CAM WITH(NOLOCK) 
	LEFT JOIN TB_CAMPEONATO_TIME CAT WITH(NOLOCK) ON CAM.SQ_CAMPEONATO = CAT.SQ_CAMPEONATO AND CAT.NR_COLOCACAO = 1
    LEFT JOIN TB_TIME TIM WITH(NOLOCK) ON CAT.SQ_TIME = TIM.SQ_TIME
	WHERE CAM.SQ_CAMPEONATO = @SQ_CAMPEONATO
	
END
GO