IF EXISTS(SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.STP_SIMULACAO_CAMPEONATO_CONSULTAR'))
   DROP PROCEDURE STP_SIMULACAO_CAMPEONATO_CONSULTAR

GO
CREATE PROCEDURE STP_SIMULACAO_CAMPEONATO_CONSULTAR(
    @SQ_CAMPEONATO INT
)
AS
BEGIN 
	SET DATEFORMAT DMY

	DECLARE @INSTRUCAO NVARCHAR(MAX)

	SET @INSTRUCAO = ' SELECT DISTINCT FAS.NM_FASE, TIM1.NM_TIME, TIM2.NM_TIME, JOG.*, ''sucesso'' AS CT_TIPO_RETORNO
                       FROM TB_JOGO JOG WITH(NOLOCK)
                       INNER JOIN TB_FASE FAS WITH(NOLOCK) ON JOG.SQ_FASE = FAS.SQ_FASE
                       INNER JOIN TB_TIME TIM1 WITH(NOLOCK) ON JOG.SQ_TIME_1 = TIM1.SQ_TIME
                       INNER JOIN TB_TIME TIM2 WITH(NOLOCK) ON JOG.SQ_TIME_2 = TIM2.SQ_TIME 
					   WHERE FAS.SQ_CAMPEONATO = ' + CAST(@SQ_CAMPEONATO AS VARCHAR(10))


	EXECUTE sp_executesql @INSTRUCAO
	
END
GO